mutation UPDATE_POST {
  updatePost(
    postId:"W4q2DBX"
    data: {
    title: "UPDATE- o título"
    body: "UPDATE- o conteúdo"
    userId:"903"

  }) {
    id
    title
    body
    user {
      firstName
    }
    indexRef
    createdAt
  }

}
