# update de user
mutation UPDATE_USER {
  updateUser(
    userId:
    data: {
      firstName:
      lastName:
      userName:
    }
  ) {
    id
    firstName
    lastName
    userName
    indexRef
    createdAt
    posts {
      id
    }
  }
}
