# para utilizar todos os campos de uma base de dados
#posso criar o fragment e coloca todos os dentro
# e para utilizar coloca-se ...post que é o nome criado para este fragment
# pode ser utilizado tanto para o user, users como para post, posts
# como no exemplo abaixo

fragment post on Post{
 id
  title
  body
  indexRef
  createdAt
  unixTimestamp

}

query GET_POST{

post1: post(id:"342") {
  ...post
  }
post2: post(id:"860") {
  ...post
  }
  post3: post(id:"15") {
  ...post
  }
 }
