# aula 34, chama o post do id e todos os posts que o id tem
 query GET_POSTS {
  posts{
       id
      title
      user {
        id
        firstName
        lastName
        userName
        indexRef
        createdAt

  }
}
}
