query GET_USERS{

users {
  id
  createdAt
  firstName
  indexRef
  lastName
  userName
  typeName

 }
}

query GET_USER{

user {
  id
  createdAt
  firstName
  indexRef
  lastName
  userName
  typeName
 }
}
